services:
  cuidado-total-api:
    container_name: cuidado-total-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - '4000:4000'
    command: >
      sh -c "npx prisma generate &&
      npx prisma migrate deploy &&
      npm run build && npm run start:prod"
