version: '3.8'

services:
  api:
    container_name: cuidado-total-api
    image: node:20-alpine
    restart: always
    tty: true
    depends_on:
      - db
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: '/usr/app'
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE_NAME=${DB_DATABASE_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PORT=${PORT}
    command: >
      sh -c "npm install &&
      npx prisma generate &&
      npx prisma migrate dev --name migration_dev &&
      npm run start:dev -- --preserveWatchOutput"

  db:
    container_name: cuidado-total-db
    image: postgres
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE_NAME}
